const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const express = require('express');
const request = require('supertest');
const jwt = require('jsonwebtoken');
const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');

test('Google auth verifies tokens, creates or links one account, and rejects invalid tokens', async t => {
  process.env.NODE_ENV = 'test';
  process.env.JWT_SECRET = 'isolated-google-session-test';
  process.env.GOOGLE_CLIENT_ID = 'isolated-google-client';
  const db = await MongoMemoryServer.create();
  await mongoose.connect(db.getUri());
  t.after(async () => { await mongoose.disconnect(); await db.stop(); });
  const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });
  const util = require('../utils/googleAuth');
  util._internal.jwksCache.keys = [{ ...publicKey.export({ format: 'jwk' }), kid: 'test-key', alg: 'RS256' }];
  util._internal.jwksCache.fetchedAt = Date.now();
  const sign = (claims = {}, options = {}) => jwt.sign({ sub: 'google-subject', email: 'google@example.test', email_verified: true, name: 'Google Tester', ...claims }, privateKey, { algorithm: 'RS256', keyid: 'test-key', audience: process.env.GOOGLE_CLIENT_ID, issuer: 'https://accounts.google.com', expiresIn: '5m', ...options });
  const app = express(); app.use(express.json()); app.use('/auth', require('../routes/authRoutes')); app.use(require('../middlewares/errorHandler').errorHandler);
  const signin = idToken => request(app).post('/auth/google').send({ idToken });
  const first = await signin(sign());
  assert.equal(first.status, 200);
  assert.ok(first.body.data.token);
  assert.equal(first.body.data.user.isEmailVerified, true);
  assert.equal(first.body.data.user.password, undefined);
  assert.equal(first.body.data.user.googleId, undefined);
  const User = require('../models/User');
  assert.equal((await signin(sign())).body.data.user._id, first.body.data.user._id);
  assert.equal(await User.countDocuments(), 1);
  assert.equal((await signin(sign({}, { audience: 'wrong-client' }))).status, 401);
  assert.equal((await signin(sign({}, { expiresIn: -1 }))).status, 401);
  assert.equal((await signin(sign({ email_verified: false }))).status, 401);
  assert.equal((await signin('not-a-jwt')).status, 401);
  await User.updateOne({ email: 'google@example.test' }, { $set: { isBlocked: true } });
  assert.equal((await signin(sign())).status, 403);
  const existing = await User.create({ username: 'existing', fullName: 'Existing User', email: 'existing@example.test', password: 'Password123!' });
  const linked = await signin(sign({ sub: 'existing-google', email: existing.email }));
  assert.equal(linked.status, 200);
  assert.equal(linked.body.data.user._id, existing.id);
  assert.equal(await User.countDocuments(), 2);
});
